# Generated by Django 5.2.8 on 2025-11-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(upload_to='datasets/')),
                ('original_filename', models.CharField(max_length=255)),
                ('summary_json', models.JSONField()),
                ('preview_rows', models.JSONField()),
                ('columns', models.JSONField()),
            ],
        ),
    ]
